// This file is generated by Slice Machine. Update with care!

import Calculator from './Calculator';
import DoubleImage from './DoubleImage';
import FaQ from './FaQ';
import FullBleed from './FullBleed';
import RepetableItems from './RepetableItems';
import SingleImage from './SingleImage';
import Story from './Story';
import StoryPreview from './StoryPreview';
import TitleDescription from './TitleDescription';

export {
	Calculator,
	DoubleImage,
	FaQ,
	FullBleed,
	RepetableItems,
	SingleImage,
	Story,
	StoryPreview,
	TitleDescription,
};

export const components = {
	calculator: Calculator,
	double_image: DoubleImage,
	fa_q: FaQ,
	full_bleed: FullBleed,
	repetable_items: RepetableItems,
	single_image: SingleImage,
	story: Story,
	story_preview: StoryPreview,
	title_description: TitleDescription,
};
