// This file is generated by Slice Machine. Update with care!

import DoubleImage from './DoubleImage';
import FaQ from './FaQ';
import FullBleed from './FullBleed';
import RepetableItems from './RepetableItems';
import SingleImage from './SingleImage';

export {
	DoubleImage,
	FaQ,
	FullBleed,
	RepetableItems,
	SingleImage,
};

export const components = {
	double_image: DoubleImage,
	fa_q: FaQ,
	full_bleed: FullBleed,
	repetable_items: RepetableItems,
	single_image: SingleImage,
};
